ServiceCivique\UserBundle\Entity\User:
    properties:
    # Your custom fields in your user entity, here is an example of fullName
        fullName:
            - NotBlank:
                message: service_civique_user.first_name.blank
                groups: [ "ServiceCiviqueProfile" ]
            - Length:
                min: 2
                minMessage: service_civique_user.first_name.short
                max: 255
                maxMessage: service_civique_user.first_name.long
                groups: [ "ServiceCiviqueProfile" ]



# Note: We still want to validate the email
# See FOSUserBundle/Resources/config/validation/orm.xml to understand
# the UniqueEntity constraint that was originally applied to both
# username and email fields
#
# As you can see, we are only applying the UniqueEntity constraint to
# the email field and not the username field.
FOS\UserBundle\Model\User:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
             fields: email
             errorPath: email
             message: fos_user.email.already_used
             groups: [ "ServiceCiviqueRegistration", "ServiceCiviqueProfile", "ServiceCiviqueRegistration2" ]

    properties:
        email:
            - NotBlank:
                message: fos_user.email.blank
                groups: [ "ServiceCiviqueRegistration", "ServiceCiviqueProfile", "ServiceCiviqueRegistration2" ]
            - Length:
                min: 2
                minMessage: fos_user.email.short
                max: 255
                maxMessage: fos_user.email.long
                groups: [ "ServiceCiviqueRegistration", "ResetPassword", "ServiceCiviqueRegistration2" ]
            - Email:
                message: fos_user.email.invalid
                groups: [ "ServiceCiviqueRegistration", "ServiceCiviqueProfile", "ServiceCiviqueRegistration2" ]
        plainPassword:
            - NotBlank:
                message: fos_user.password.blank
                groups: [ "ServiceCiviqueRegistration", "ResetPassword", "ChangePassword" ]
            - Length:
                min: 2
                minMessage: fos_user.password.blank
                groups: [ "ServiceCiviqueRegistration", "ServiceCiviqueProfile", "ResetPassword", "ChangePassword"]
            - Blank:
                message: fos_user.password.blank
                groups: [ "ServiceCiviqueRegistration2"]

FOS\UserBundle\Model\Group:
    properties:
        name:
            - NotBlank:
                message: fos_user.group.blank
                groups: [ "ServiceCiviqueRegistration" ]
            - Length:
                min: 2
                minMessage: fos_user.group.short
                max: 255
                maxMessage: fos_user.group.long
                groups: [ "ServiceCiviqueRegistration" ]
