ServiceCivique\Bundle\ContentBundle\Entity\StaticContent:
    type: entity
    table: static_content
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        title:
            type: string
            length: 255
        content:
            type: text
        slug:
            type: string
            length: 255
            gedmo:
                slug:
                    fields: ['title']
        created:
            type: datetime
            gedmo:
                timestampable:
                    on: create
        updated:
            type: datetime
            gedmo:
                timestampable:
                    on: update
    lifecycleCallbacks: {  }
