ServiceCivique\Bundle\CoreBundle\Entity\ApprovalConflict:
    type: entity
    table: approval_conflict
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        approvalNumber:
            type: string
            length: 255
            column: approval_number
        problemType:
            type: integer
            column: problem_type
        organizationName:
            type: string
            length: 255
            column: organization_name
        contactEmail:
            type: string
            length: 255
            column: contact_email
        firstname:
            type: string
            length: 255
        lastname:
            type: string
            length: 255
        comment:
            type: text
        isResolved:
            type: integer
            column: is_resolved
    lifecycleCallbacks: {  }
