ServiceCivique\Bundle\CoreBundle\Entity\Media:
    type: entity
    table: media
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    properties:
        file:
            - File:
                maxSize: 10M
    fields:
        title:
            type: string
            length: 255
        type:
            type: integer
        mediaName:
            type: string
            length: 255
            column: media_name
        url:
            type: string
            length: 255
            nullable: true
        published:
            type: datetime
            # gedmo:
            #     timestampable:
            #         on: create
    lifecycleCallbacks:
        prePersist:  [ preUpload ]
        preUpdate:   [ preUpload ]
        postPersist: [ upload ]
        postUpdate:  [ upload ]
        postRemove:  [ removeUpload ]
