service_civique_content:
    resource: "@ServiceCiviqueContentBundle/Resources/config/routing.yml"
    prefix:   /

service_civique_addressing:
    resource: "@ServiceCiviqueAddressingBundle/Resources/config/routing/routing.yml"
    prefix:   /

service_civique_key_value_store:
    resource: "@ServiceCiviqueKeyValueStoreBundle/Resources/config/routing.xml"
    prefix:   /

service_civique_contact:
    resource: "@ServiceCiviqueContactBundle/Resources/config/routing.yml"
    prefix:   /

service_civique_web:
    resource: "@ServiceCiviqueWebBundle/Resources/config/routing/routing.yml"
    prefix:   /

polem_departements:
    resource: "@PolemDepartementsBundle/Resources/config/routing.yml"
    prefix:   /

lns_menu:
    resource: "@LnsMenuBundle/Resources/config/routing/routing.yml"
    prefix:   /

sylius_taxonomy:
    resource: @SyliusTaxonomyBundle/Resources/config/routing.yml
    prefix: /taxonomies

service_civique_user:
    resource: "@ServiceCiviqueUserBundle/Resources/config/routing.yml"

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /jeunes/profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /jeunes/register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile

lexik_translation_edition:
    resource: "@LexikTranslationBundle/Resources/config/routing.yml"
    prefix:   /administration/texts

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"

_imagine:
    resource: .
    type:     imagine

_security_check_special:
    pattern:  /organismes/login_check

_security_logout_special:
    pattern:  /organismes/logout


_monitor:
    resource: "@LiipMonitorBundle/Resources/config/routing.xml"
    prefix: /monitor/health
