service_civique_backend_advantage_index:
    pattern: /
    methods: [GET]
    defaults:
        _controller: service_civique.controller.advantage:indexAction
        _sylius:
            template: ServiceCiviqueWebBundle:Backend/Advantage:index.html.twig
            sortable: true
            paginate: 20
            sorting:
                id: desc

service_civique_backend_advantage_create:
    pattern: /new
    methods: [GET, POST]
    defaults:
        _controller: service_civique.controller.advantage:createAction
        _sylius:
            template: ServiceCiviqueWebBundle:Backend/Advantage:create.html.twig
            redirect: service_civique_backend_advantage_index

service_civique_backend_advantage_update:
    pattern: /{id}/edit
    methods: [GET, PUT, POST]
    defaults:
        _controller: service_civique.controller.advantage:updateAction
        _sylius:
            template: ServiceCiviqueWebBundle:Backend/Advantage:update.html.twig
            redirect: service_civique_backend_advantage_index

service_civique_backend_advantage_delete:
    pattern: /{id}
    methods: [DELETE]
    defaults:
        _controller: service_civique.controller.advantage:deleteAction
        _sylius:
            redirect: service_civique_backend_advantage_index
