service_civique_partner_list:
    pattern: /
    methods: [GET]
    defaults:
        _controller: service_civique.controller.partner:indexAction
        _sylius:
            template: ServiceCiviqueWebBundle:Frontend/Partner:list.html.twig
            paginate: false
            limit: 99
            sorting:
                title: asc

service_civique_partner_show:
    pattern: /{slug}
    methods: [GET]
    defaults:
        _controller: service_civique.controller.partner:showAction
        _sylius:
            template: ServiceCiviqueWebBundle:Frontend/Partner:show.html.twig
