<?php

namespace ServiceCivique\Bundle\CoreBundle\Repository;

use Sylius\Bundle\ResourceBundle\Doctrine\ORM\EntityRepository;

/**
 * ActuRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ActuRepository extends EntityRepository
{
     public function findLast()
    {
        $qb = $this->createQueryBuilder('a');

        $qb
            ->orderBy('a.published', 'DESC')
            ->setMaxResults(1);
        ;

        return $qb->getQuery()->getSingleResult();
    }
}
