<?php

namespace ServiceCivique\Bundle\CoreBundle\Repository;

use Sylius\Bundle\ResourceBundle\Doctrine\ORM\EntityRepository;
use Doctrine\ORM\QueryBuilder;
use Pagerfanta\Adapter\DoctrineORMAdapter;
use Pagerfanta\Pagerfanta;

/**
 * ApprovalConflictRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ApprovalConflictRepository extends EntityRepository
{
    public function findNotResolved()
    {
        $qb = $this->createQueryBuilder('a');

        $qb
            ->where('a.isResolved = 0')
            ->orderBy('a.id', 'DESC')
        ;

        return $this->getPaginator($qb);
        // return $qb->getQuery()->getResult();
    }

    public function getPaginator(QueryBuilder $queryBuilder)
    {
        return new Pagerfanta(new DoctrineORMAdapter($queryBuilder, false));
    }
}
