<?php

namespace ServiceCivique\Bundle\CoreBundle\Repository;

use Sylius\Bundle\ResourceBundle\Doctrine\ORM\EntityRepository;

/**
 * ApprovalRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ApprovalRepository extends EntityRepository
{
    public function findOneByApprovalNumber($criteria)
    {
        $query = $this->getEntityManager()
            ->createQuery('
                SELECT a FROM ServiceCiviqueCoreBundle:Approval a WHERE a.approvalNumber = :approvalNumber'
            )
                ->setParameter('approvalNumber', $criteria['approval_number'])
        ;

        try {
            return $query->getSingleResult();
        } catch (\Doctrine\ORM\NoResultException $e) {
            return null;
        }
    }

    public function getAllCount()
    {
        return $this->createQueryBuilder('a')
            ->select('count(a.id)')
            ->where('a.review = :review')
               ->setParameter('review', 'Avis Favorable')
            ->andWhere('a.decisionDate > :now')
               ->setParameter('now', new \DateTime())
            ->getQuery()
            ->getSingleScalarResult();
    }

    public function getAllWithBatch($offset = 0, $max = 100)
    {
        $queryBuilder = $this->createQueryBuilder('a');

        $queryBuilder
            ->where('a.review = :review')
               ->setParameter('review', 'Avis Favorable')
            ->andWhere('a.decisionDate < :now')
               ->setParameter('now', new \DateTime())
            ->setMaxResults($max)
            ->setFirstResult($offset)
        ;

        return $queryBuilder
            ->getQuery()
            ->getResult()
        ;
    }
}
