<?php

namespace ServiceCivique\Bundle\CoreBundle\Repository;

use Sylius\Bundle\ResourceBundle\Doctrine\ORM\EntityRepository;

/**
 * ForbiddenKeywordRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ForbiddenKeywordRepository extends EntityRepository {

    public function findAllAndReturnsNames() {
        $queryBuilder = $this->getQueryBuilder();

        return $queryBuilder
            ->select('o.name')
            ->getQuery()
            ->getArrayResult();
    }

}
