<?php

namespace ServiceCivique\Bundle\CoreBundle\Repository;

use Sylius\Bundle\ResourceBundle\Doctrine\ORM\EntityRepository;

/**
 * HeaderRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HeaderRepository extends EntityRepository
{
    public function findOneRandom()
    {
        $datetime = new \Datetime();
        $queryBuilder = $this->createQueryBuilder('e');

        $queryBuilder
            ->andWhere('e.startDate IS NULL OR e.startDate <= :sart_date_offset')
            ->setParameter('sart_date_offset', $datetime->format('Y-m-d'))
            ->andWhere('e.endDate IS NULL OR e.endDate >= :end_date_offset')
            ->setParameter('end_date_offset', $datetime->format('Y-m-d'));

        $results = $queryBuilder
            ->getQuery()
            ->useResultCache(true, 24 * 60 * 60, sprintf('random_header_%s', $datetime->format('Y-m-d')))
            ->getResult();

        return $this->getRandomResult($results);
    }

    /**
     *
     */
    protected function getRandomResult($results)
    {
        if (count($results)) {
            $events = array();
            foreach ($results as $result) {
                if ($result->getEndDate() != null) {
                    $events[] = $result;
                }
            }
            $dataSet = count($events) ? $events : $results;
            $randKey = array_rand($dataSet);

            return $dataSet[$randKey];
        }

        return null;
    }
}
