<?php

namespace ServiceCivique\Bundle\CoreBundle\Repository;

use Sylius\Bundle\ResourceBundle\Doctrine\ORM\EntityRepository;
use Doctrine\ORM\QueryBuilder;
use Pagerfanta\Adapter\DoctrineORMAdapter;
use Pagerfanta\Pagerfanta;

/**
 * MediaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MediaRepository extends EntityRepository
{
    public function findLast()
    {
        $qb = $this->createQueryBuilder('m');

        $qb
            ->orderBy('m.published', 'DESC')
            ->setMaxResults(2);
        ;

        return $qb->getQuery()->getResult();
    }

    public function findFiltered($type)
    {
        $types = array(
            'presse'     => 1,
            'radio'      => 2,
            'television' => 3,
        );

        $queryBuilder = $this->getQueryBuilder()
            ->where($this->getAlias() . '.type = :type')
                ->setParameter('type', $types[$type])
            ->orderBy($this->getAlias() . '.published', 'DESC')
        ;

        return $this->getPaginator($queryBuilder);
    }

    public function getPaginator(QueryBuilder $queryBuilder)
    {
        return new Pagerfanta(new DoctrineORMAdapter($queryBuilder, false));
    }
}
